# Generated by Django 4.2.5 on 2023-11-13 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dishwasher', models.BooleanField(default=False)),
                ('dry', models.BooleanField(default=False)),
                ('freezer', models.BooleanField(default=False)),
                ('garbage_disposal', models.BooleanField(default=False)),
                ('micro_wave', models.BooleanField(default=False)),
                ('oven', models.BooleanField(default=False)),
                ('refrigerator', models.BooleanField(default=False)),
                ('trash_compator', models.BooleanField(default=False)),
                ('washer', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ArchitecturalStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bungalow', models.BooleanField(default=False)),
                ('modern', models.BooleanField(default=False)),
                ('villa', models.BooleanField(default=False)),
                ('loft', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Basement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finished', models.BooleanField(default=False)),
                ('unfinished', models.BooleanField(default=False)),
                ('partially_finished', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gated_entry', models.BooleanField(default=False)),
                ('near_transportation', models.BooleanField(default=False)),
                ('controlled_access', models.BooleanField(default=False)),
                ('storage', models.BooleanField(default=False)),
                ('elevator', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Exterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brick', models.BooleanField(default=False)),
                ('cement', models.BooleanField(default=False)),
                ('wood', models.BooleanField(default=False)),
                ('stone', models.BooleanField(default=False)),
                ('stucco', models.BooleanField(default=False)),
                ('metal', models.BooleanField(default=False)),
                ('vinyl', models.BooleanField(default=False)),
                ('other_exterior', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='FloorCovering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carpet', models.BooleanField(default=False)),
                ('concrete', models.BooleanField(default=False)),
                ('hardwood', models.BooleanField(default=False)),
                ('laminate', models.BooleanField(default=False)),
                ('linoleum', models.BooleanField(default=False)),
                ('softwood', models.BooleanField(default=False)),
                ('tile', models.BooleanField(default=False)),
                ('slate', models.BooleanField(default=False)),
                ('other_floor_covering', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GeoCordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.CharField()),
                ('longitude', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='IndoorFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('security_system', models.BooleanField(default=False)),
                ('cable', models.BooleanField(default=False)),
                ('ceiling_fans', models.BooleanField(default=False)),
                ('fire_place', models.BooleanField(default=False)),
                ('wired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Locality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pincode', models.IntegerField()),
                ('unit', models.CharField()),
                ('district', models.CharField()),
                ('state', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='OpenHouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='OutdoorAmenities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balcony', models.BooleanField(default=False)),
                ('barbecue_area', models.BooleanField(default=False)),
                ('pond', models.BooleanField(default=False)),
                ('pool', models.BooleanField(default=False)),
                ('porch', models.BooleanField(default=False)),
                ('rv_parking', models.BooleanField(default=False)),
                ('water_front', models.BooleanField(default=False)),
                ('spa', models.BooleanField(default=False)),
                ('sprinkler_system', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carport', models.BooleanField(default=False)),
                ('off_street', models.BooleanField(default=False)),
                ('on_street', models.BooleanField(default=False)),
                ('garage_attached', models.BooleanField(default=False)),
                ('garage_detached', models.BooleanField(default=False)),
                ('parking_spaces', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PropertyAccounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('down_payment', models.CharField(blank=True, null=True)),
                ('loan_years', models.CharField(blank=True, null=True)),
                ('interest_rate', models.CharField(blank=True, null=True)),
                ('tax_rate', models.CharField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Roof',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_up', models.BooleanField(default=False)),
                ('asphalt', models.BooleanField(default=False)),
                ('concrete', models.BooleanField(default=False)),
                ('slate', models.BooleanField(default=False)),
                ('tile', models.BooleanField(default=False)),
                ('composition', models.BooleanField(default=False)),
                ('metal', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dining_room', models.BooleanField(default=False)),
                ('family_room', models.BooleanField(default=False)),
                ('laundry_room', models.BooleanField(default=False)),
                ('library', models.BooleanField(default=False)),
                ('breakfast_nook', models.BooleanField(default=False)),
                ('office', models.BooleanField(default=False)),
                ('recreation_room', models.BooleanField(default=False)),
                ('master_room', models.BooleanField(default=False)),
                ('pantry', models.BooleanField(default=False)),
                ('workshop', models.BooleanField(default=False)),
                ('total_rooms', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='View',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.BooleanField(default=False)),
                ('mountain', models.BooleanField(default=False)),
                ('park', models.BooleanField(default=False)),
                ('territorial', models.BooleanField(default=False)),
                ('water', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField()),
                ('email', models.CharField()),
                ('related_website', models.CharField(blank=True, null=True)),
                ('property_name', models.CharField()),
                ('transaction_type', models.CharField()),
                ('property_type', models.CharField()),
                ('price', models.CharField()),
                ('address', models.CharField()),
                ('virtual_tour_url', models.CharField(blank=True, null=True)),
                ('lot_size', models.CharField()),
                ('basement_square_feet', models.CharField(blank=True, null=True)),
                ('garage_square_feet', models.CharField(blank=True, null=True)),
                ('finished_square_feet', models.CharField(blank=True, null=True)),
                ('description', models.CharField()),
                ('more_description', models.CharField()),
                ('year_build', models.DateField(blank=True, null=True)),
                ('remodal_year', models.DateField(blank=True, null=True)),
                ('bedroom', models.IntegerField(blank=True, null=True)),
                ('bathroom', models.IntegerField(blank=True, null=True)),
                ('accounts', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='data.propertyaccounts')),
                ('appliances', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appliances', to='data.appliances')),
                ('architectural_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='architectural_style', to='data.architecturalstyle')),
                ('basement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='basement', to='data.basement')),
                ('building_amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_amenities', to='data.buildingamenities')),
                ('coordinates', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coordinates', to='data.geocordinates')),
                ('exterior', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exterior', to='data.exterior')),
                ('floor_covering', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floor_covering', to='data.floorcovering')),
                ('indoor_features', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indoor_features', to='data.indoorfeatures')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locality', to='data.locality')),
                ('open_house', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='open_house', to='data.openhouse')),
                ('outdoor_amenities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outdoor_amenities', to='data.outdooramenities')),
                ('parking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parking', to='data.parking')),
                ('roof', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roof', to='data.roof')),
                ('rooms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='data.rooms')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_id', to=settings.AUTH_USER_MODEL)),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view', to='data.view')),
            ],
        ),
        migrations.CreateModel(
            name='Documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Property Image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='data.property')),
            ],
        ),
    ]
