# Generated by Django 4.2.5 on 2023-11-15 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='property',
            name='posted_on',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
