# Generated by Django 4.2.5 on 2023-11-15 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_property_is_active_property_posted_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Property Image'),
        ),
    ]
