# Generated by Django 4.2.5 on 2023-11-15 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_documents_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='image',
            field=models.ImageField(default=0, upload_to='images/', verbose_name='Property Image'),
            preserve_default=False,
        ),
    ]
