# Generated by Django 4.2.5 on 2023-11-18 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_property_favourites'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='favourites',
        ),
    ]
