# Generated by Django 4.2.7 on 2023-12-22 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_remove_property_favourites'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='more_description',
            field=models.CharField(blank=True),
        ),
    ]
