# Generated by Django 4.2.7 on 2023-11-23 16:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_favourites'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_read_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 23, 16, 8, 58, 103316, tzinfo=datetime.timezone.utc)),
        ),
    ]
