# Generated by Django 4.2.7 on 2023-11-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_user_last_read_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='last_read_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
